AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An example RESTful service

Resources:

  FunctionGetApex:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: functions/version.handler
      Events:
        GetApex:
          Type: Api
          Properties:
            Path: /
            Method: GET